"""clear-amber-heron — generated by Cook.

A FastAPI app with PostgreSQL.

The user's prompt is carried as data (see ``USER_INTENT`` in ``service.app``),
never spliced into a docstring or comment — a verbatim prompt can contain
anything, including a ``\"\"\"`` that would otherwise end this string early.
"""

__version__ = "0.1.0"
