"""Which build of this application is running. Written by Cook, never by an agent.

Aiven reports `application_deployment_commit_sha` only for services created with a
VCS integration. Verified across eight application services in one project: all
three with an integration report a commit, and all five without report `null` —
even with the build SUCCESS and the deployment COMPLETED. Cook's generated apps
have no integration on purpose, because a public repository needs no credential for
Aiven's builder to read, so for them that field is always empty and Cook cannot use
it to tell which code is serving.

So the application says so itself, on `/healthz`.

**Why a stamp and not the commit SHA.** The SHA of a commit covers every file in
it, including this one, so a file containing its own commit's SHA cannot be written
before the commit is made. The stamp is generated by Cook per push instead: it goes
into the tree, the commit covers it, the container is built from that commit, and
the running process reports it back. Cook compares what it pushed with what
answered.

That proves more than a commit SHA would. A SHA in Aiven's metadata is Aiven's
bookkeeping about a build; this is the process that is serving requests telling you
which source it was built from.
"""

REVISION = "96758f0d929e"
